# Common keys in output JSON
WINRATE = "winrate"
WINS = "wins"
GAMES = "games"
ROUNDS = "rounds"
MAPS = "maps"
ACS = "acs"
SCORE = "score"
TOP_AGENTS = "top_agents"
TOP_ROLES = "top_roles"
AGENT = "agent"
AGENTS = "agents"
FULL_BODY_IMAGE_URL = "full_body_image_url"
ROLES = "roles"
ROLE = "role"

KILLS = "kills"
ASSISTS = "assists"
ASSISTS_PER_STANDARD_GAME = "assists_per_standard_game"
DEATHS = "deaths"
PLANTS = "plants"
DEFUSES = "defuses"
FIRST_KILLS = "first_kills"
FIRST_DEATHS = "first_deaths"
PERCENTAGE = "percentage"
COMMITTED = "committed"
WITNESSED = "witnessed"
