# Keys in output JSON
TEAMMATE_NAME = "teammate_name"
OPPONENT_NAME = "opponent_name"
ASSISTANT_NAME = "assistant_name"
ASSISTED_NAME = "assisted_name"

WINRATE = "winrate"
WINS = "wins"
GAMES = "games"
ROUNDS = "rounds"
TOP_AGENTS = "top_agents"
TOP_ROLES = "top_roles"
AGENT = "agent"
AGENTS = "agents"
FULL_BODY_IMAGE_URL = "full_body_image_url"
ROLES = "roles"
ROLE = "role"

KILLS = "kills"
ASSISTS = "assists"
ASSISTS_PER_STANDARD_GAME = "assists_per_standard_game"
DEATHS = "deaths"
FIRST_KILLS = "first_kills"
FIRST_DEATHS = "first_deaths"
PERCENTAGE = "percentage"
COMMITTED = "committed"
WITNESSED = "witnessed"
