# Player names used as keys in output JSON
ANDY = "andy"
BRANDON = "brandon"
BREE = "bree"
BRIAN = "brian"
CADE = "cade"
DARWIN = "darwin"
JOSH = "josh"
LINDSEY = "lindsey"
SEQUENTIAL = "sequential"
SOPHIE = "sophie"
STEVE = "steve"
STEVEN = "steven"
SUN = "sun"
SUSI = "susi"
SUSU = "susu"
TANG = "tang"
YANG = "yang"
